// This file is auto-generated by @hey-api/openapi-ts

export type BearerResponse = {
  access_token: string;
  token_type: string;
};

export type Body_auth_reset_forgot_password = {
  email: string;
};

export type Body_auth_reset_reset_password = {
  token: string;
  password: string;
};

export type Body_auth_verify_request_token = {
  email: string;
};

export type Body_auth_verify_verify = {
  token: string;
};

/**
 * 爬取任务请求
 */
export type CrawlTaskRequest = {
  /**
   * 任务名称
   */
  task_name: string;
  /**
   * 搜索关键词
   */
  keyword: string;
  /**
   * 目标爬取数量
   */
  target_count?: number;
  /**
   * 排序方式
   */
  sort_type?: number;
  /**
   * 自定义cookies
   */
  cookies?: string | null;
  /**
   * 接收结果的webhook URL
   */
  webhook_url?: string | null;
};

export type ErrorModel = {
  detail:
    | string
    | {
        [key: string]: string;
      };
};

export type HTTPValidationError = {
  detail?: Array<ValidationError>;
};

export type ItemCreate = {
  name: string;
  description?: string | null;
  quantity?: number | null;
};

export type ItemRead = {
  name: string;
  description?: string | null;
  quantity?: number | null;
  id: string;
  user_id: string;
};

export type KeywordCreate = {
  keyword: string;
  category?: string | null;
  weight?: number;
  is_active?: boolean;
  description?: string | null;
};

export type KeywordListResponse = {
  keywords: Array<KeywordResponse>;
  total: number;
  categories: Array<string>;
};

export type KeywordResponse = {
  keyword: string;
  category?: string | null;
  weight?: number;
  is_active?: boolean;
  description?: string | null;
  id: string;
  created_at: string;
  updated_at: string;
};

export type KeywordUpdate = {
  keyword?: string | null;
  category?: string | null;
  weight?: number | null;
  is_active?: boolean | null;
  description?: string | null;
};

export type login = {
  grant_type?: string | null;
  username: string;
  password: string;
  scope?: string;
  client_id?: string | null;
  client_secret?: string | null;
};

/**
 * 笔记统计响应
 */
export type NoteStatsResponse = {
  total_notes: number;
  new_notes: number;
  changed_notes: number;
  important_notes: number;
  today_crawled: number;
};

/**
 * 任务操作响应
 */
export type TaskActionResponse = {
  success: boolean;
  message: string;
  task_id?: string | null;
  github_run_url?: string | null;
};

/**
 * 创建任务请求
 */
export type TaskCreate = {
  /**
   * 任务名称
   */
  task_name: string;
  /**
   * 搜索关键词
   */
  keyword: string;
  /**
   * 目标爬取数量
   */
  target_count?: number;
  /**
   * 排序方式
   */
  sort_type?: number;
  /**
   * 自定义cookies
   */
  cookies?: string | null;
  /**
   * webhook回调URL
   */
  webhook_url?: string | null;
};

/**
 * 任务列表响应
 */
export type TaskListResponse = {
  tasks: Array<TaskResponse>;
  total: number;
  page: number;
  size: number;
};

/**
 * 任务响应
 */
export type TaskResponse = {
  /**
   * 任务名称
   */
  task_name: string;
  /**
   * 搜索关键词
   */
  keyword: string;
  /**
   * 目标爬取数量
   */
  target_count?: number;
  /**
   * 排序方式
   */
  sort_type?: number;
  /**
   * 自定义cookies
   */
  cookies?: string | null;
  /**
   * 任务ID
   */
  id: string;
  /**
   * 任务状态
   */
  status: TaskStatusEnum;
  /**
   * 任务创建者ID
   */
  owner_id: string;
  /**
   * 总爬取数量
   */
  total_crawled?: number;
  /**
   * 新笔记数量
   */
  new_notes?: number;
  /**
   * 变更笔记数量
   */
  changed_notes?: number;
  /**
   * 重要笔记数量
   */
  important_notes?: number;
  /**
   * 错误信息
   */
  error_message?: string | null;
  /**
   * 计划执行时间
   */
  scheduled_time?: string | null;
  /**
   * 开始执行时间
   */
  started_at?: string | null;
  /**
   * 完成时间
   */
  finished_at?: string | null;
  /**
   * 创建时间
   */
  created_at: string;
  /**
   * 更新时间
   */
  updated_at: string;
};

/**
 * 任务统计响应
 */
export type TaskStatsResponse = {
  total_tasks: number;
  pending_tasks: number;
  running_tasks: number;
  completed_tasks: number;
  failed_tasks: number;
};

/**
 * 任务状态枚举
 */
export type TaskStatusEnum = "pending" | "running" | "completed" | "failed";

/**
 * 任务触发响应
 */
export type TaskTriggerResponse = {
  success: boolean;
  message: string;
  task_id?: string | null;
  github_run_url?: string | null;
};

export type UserCreate = {
  email: string;
  password: string;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type UserRead = {
  id: string;
  email: string;
  is_active?: boolean;
  is_superuser?: boolean;
  is_verified?: boolean;
};

export type UserUpdate = {
  password?: string | null;
  email?: string | null;
  is_active?: boolean | null;
  is_superuser?: boolean | null;
  is_verified?: boolean | null;
};

export type ValidationError = {
  loc: Array<string | number>;
  msg: string;
  type: string;
};

/**
 * 完整的Webhook请求模式
 */
export type WebhookRequest = {
  data?:
    | XhsNoteData
    | Array<XhsNoteData>
    | {
        [key: string]: unknown;
      }
    | null;
  status: WebhookStatus;
  message: string;
  timestamp: string;
  run_id: string;
  task_id?: string | null;
  elapsed_time?: number | null;
  progress?: number | null;
};

/**
 * Webhook响应
 */
export type WebhookResponse = {
  status?: string;
  message?: string;
  processed_count?: number | null;
  errors?: Array<string> | null;
};

/**
 * Webhook状态枚举
 */
export type WebhookStatus =
  | "started"
  | "progress"
  | "success"
  | "error"
  | "completed"
  | "failed";

/**
 * 小红书笔记数据 - 爬取原始数据
 */
export type XhsNoteData = {
  note_id: string;
  note_url?: string | null;
  note_type?: string | null;
  author_user_id?: string | null;
  author_nickname?: string | null;
  author_avatar?: string | null;
  title?: string | null;
  desc?: string | null;
  tags?: Array<string> | null;
  upload_time?: string | null;
  ip_location?: string | null;
  liked_count?: number;
  collected_count?: number;
  comment_count?: number;
  share_count?: number;
  video_cover?: string | null;
  video_addr?: string | null;
  image_list?: Array<string> | null;
  xsec_token?: string | null;
};

/**
 * 笔记响应模式
 */
export type XhsNoteResponse = {
  id: string;
  note_id: string;
  note_url: string | null;
  note_type: string | null;
  title: string | null;
  desc: string | null;
  author_nickname: string | null;
  liked_count: number;
  comment_count: number;
  current_tags: Array<string> | null;
  is_new: boolean;
  is_changed: boolean;
  is_important: boolean;
  first_crawl_time: string;
  last_crawl_time: string;
};

export type AuthJwtLoginData = {
  body: login;
};

export type AuthJwtLoginResponse = BearerResponse;

export type AuthJwtLoginError = ErrorModel | HTTPValidationError;

export type AuthJwtLogoutResponse = unknown;

export type AuthJwtLogoutError = unknown;

export type RegisterRegisterData = {
  body: UserCreate;
};

export type RegisterRegisterResponse = UserRead;

export type RegisterRegisterError = ErrorModel | HTTPValidationError;

export type ResetForgotPasswordData = {
  body: Body_auth_reset_forgot_password;
};

export type ResetForgotPasswordResponse = unknown;

export type ResetForgotPasswordError = HTTPValidationError;

export type ResetResetPasswordData = {
  body: Body_auth_reset_reset_password;
};

export type ResetResetPasswordResponse = unknown;

export type ResetResetPasswordError = ErrorModel | HTTPValidationError;

export type VerifyRequestTokenData = {
  body: Body_auth_verify_request_token;
};

export type VerifyRequestTokenResponse = unknown;

export type VerifyRequestTokenError = HTTPValidationError;

export type VerifyVerifyData = {
  body: Body_auth_verify_verify;
};

export type VerifyVerifyResponse = UserRead;

export type VerifyVerifyError = ErrorModel | HTTPValidationError;

export type UsersCurrentUserResponse = UserRead;

export type UsersCurrentUserError = unknown;

export type UsersPatchCurrentUserData = {
  body: UserUpdate;
};

export type UsersPatchCurrentUserResponse = UserRead;

export type UsersPatchCurrentUserError =
  | ErrorModel
  | unknown
  | HTTPValidationError;

export type UsersUserData = {
  path: {
    id: string;
  };
};

export type UsersUserResponse = UserRead;

export type UsersUserError = unknown | HTTPValidationError;

export type UsersPatchUserData = {
  body: UserUpdate;
  path: {
    id: string;
  };
};

export type UsersPatchUserResponse = UserRead;

export type UsersPatchUserError = ErrorModel | unknown | HTTPValidationError;

export type UsersDeleteUserData = {
  path: {
    id: string;
  };
};

export type UsersDeleteUserResponse = void;

export type UsersDeleteUserError = unknown | HTTPValidationError;

export type ReadItemResponse = Array<ItemRead>;

export type ReadItemError = unknown;

export type CreateItemData = {
  body: ItemCreate;
};

export type CreateItemResponse = ItemRead;

export type CreateItemError = HTTPValidationError;

export type DeleteItemData = {
  path: {
    item_id: string;
  };
};

export type DeleteItemResponse = unknown;

export type DeleteItemError = HTTPValidationError;

export type GetKeywordsData = {
  query?: {
    active_only?: boolean;
    category?: string | null;
    limit?: number;
    search?: string | null;
    skip?: number;
  };
};

export type GetKeywordsResponse = KeywordListResponse;

export type GetKeywordsError = HTTPValidationError;

export type CreateKeywordData = {
  body: KeywordCreate;
};

export type CreateKeywordResponse = KeywordResponse;

export type CreateKeywordError = HTTPValidationError;

export type UpdateKeywordData = {
  body: KeywordUpdate;
  path: {
    keyword_id: string;
  };
};

export type UpdateKeywordResponse = KeywordResponse;

export type UpdateKeywordError = HTTPValidationError;

export type DeleteKeywordData = {
  path: {
    keyword_id: string;
  };
};

export type DeleteKeywordResponse = unknown;

export type DeleteKeywordError = HTTPValidationError;

export type ToggleKeywordStatusData = {
  path: {
    keyword_id: string;
  };
};

export type ToggleKeywordStatusResponse = unknown;

export type ToggleKeywordStatusError = HTTPValidationError;

export type GetCategoriesResponse = Array<string>;

export type GetCategoriesError = unknown;

export type GetKeywordStatsResponse = unknown;

export type GetKeywordStatsError = unknown;

export type ReceiveXhsWebhookData = {
  body: WebhookRequest;
};

export type ReceiveXhsWebhookResponse = WebhookResponse;

export type ReceiveXhsWebhookError = HTTPValidationError;

export type TestWebhookResponse = unknown;

export type TestWebhookError = unknown;

export type GetNotesStatsResponse = NoteStatsResponse;

export type GetNotesStatsError = unknown;

export type SearchNotesData = {
  query?: {
    author_user_id?: string;
    is_changed?: boolean;
    is_important?: boolean;
    is_new?: boolean;
    keyword?: string;
    limit?: number;
    offset?: number;
  };
};

export type SearchNotesResponse = Array<XhsNoteResponse>;

export type SearchNotesError = HTTPValidationError;

export type GetNoteDetailData = {
  path: {
    note_id: string;
  };
};

export type GetNoteDetailResponse = unknown;

export type GetNoteDetailError = HTTPValidationError;

export type TriggerCrawlTaskData = {
  body: CrawlTaskRequest;
};

export type TriggerCrawlTaskResponse = TaskTriggerResponse;

export type TriggerCrawlTaskError = HTTPValidationError;

export type GetTasksData = {
  query?: {
    keyword?: string | null;
    page?: number;
    size?: number;
    status?: string | null;
  };
};

export type GetTasksResponse = TaskListResponse;

export type GetTasksError = HTTPValidationError;

export type CreateTaskData = {
  body: TaskCreate;
};

export type CreateTaskResponse = TaskActionResponse;

export type CreateTaskError = HTTPValidationError;

export type GetTaskStatsResponse = TaskStatsResponse;

export type GetTaskStatsError = unknown;

export type GetTaskDetailData = {
  path: {
    task_id: string;
  };
};

export type GetTaskDetailResponse = TaskResponse;

export type GetTaskDetailError = HTTPValidationError;

export type CancelTaskData = {
  path: {
    task_id: string;
  };
};

export type CancelTaskResponse = TaskActionResponse;

export type CancelTaskError = HTTPValidationError;
