# This file is for production deployment
# It should be used with the base docker-compose.yml:
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  backend:
    image: ${ALIYUN_REGISTRY_URL}/${ALIYUN_NAMESPACE}/backend:latest
    command: sh /start.prod.sh
    restart: always

  frontend:
    image: ${ALIYUN_REGISTRY_URL}/${ALIYUN_NAMESPACE}/frontend:latest
    restart: always

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - my_network 