# This file is for local development overrides
services:
  backend:
    command: sh start.sh
    ports:
      - "8000:8000"
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json

  frontend:
    command: sh start.sh
    ports:
      - "3000:3000" 
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json