services:
  backend:
    image: xiuer-backend:local
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - TEST_DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5433/testdatabase
      - MAIL_SERVER=localhost
      - AUTO_MIGRATE=true
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - RESET_PASSWORD_SECRET_KEY=${RESET_PASSWORD_SECRET_KEY}
      - VERIFICATION_SECRET_KEY=${VERIFICATION_SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - FRONTEND_URL=${FRONTEND_URL}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    networks:
      - my_network
    depends_on:
      - db

  db:
    image: postgres:17
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    image: xiuer-frontend:local
    user: node
    networks:
      - my_network
    environment:
      NODE_ENV: development
      API_BASE_URL: http://backend:8000

volumes:
  postgres_data:
  nextjs-node-modules:
  fastapi-venv:

networks:
  my_network:
    driver: bridge 