# This file is for local development overrides
services:
  backend:
    build:
      context: ./fastapi_backend
      dockerfile: Dockerfile
    command: sh start.sh
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_backend:/app
      - fastapi-venv:/app/.venv
      - ./local-shared-data:/app/shared-data
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
    restart: always

  frontend:
    build:
      context: ./nextjs-frontend
      dockerfile: Dockerfile.dev
      args:
        - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
    command: sh start.sh
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
    restart: always

  db:
    ports:
      - "5432:5432"
    restart: always

  db_test:
    image: postgres:17
    environment:
      POSTGRES_USER: xiuer_user
      POSTGRES_PASSWORD: Dingjunjie123
      POSTGRES_DB: xiuer_db
    ports:
      - "5433:5432"
    networks:
      - my_network
    restart: always