services:
  backend:
    build:
      context: fastapi_backend
    environment:
      - OPENAPI_OUTPUT_FILE=./shared-data/openapi.json
      - DATABASE_URL=postgresql+asyncpg://postgres:password@db:5432/mydatabase
      - TEST_DATABASE_URL=postgresql+asyncpg://postgres:password@db:5433/testdatabase
      - MAIL_SERVER=mailhog
      - AUTO_MIGRATE=false  # Set to 'true' to enable automatic migrations on startup
      # GitHub 配置
      - GITHUB_TOKEN=${GITHUB_TOKEN:-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}  # 从环境变量读取
      - GITHUB_REPO_OWNER=${GITHUB_REPO_OWNER:-JunJD}  # 默认 JunJD
      - GITHUB_REPO_NAME=${GITHUB_REPO_NAME:-xiuer-spider}  # 默认 xiuer-spider
    ports:
      - "8000:8000"
    networks:
      - my_network
    volumes:
      - ./fastapi_backend:/app
      - fastapi-venv:/app/.venv
      - ./local-shared-data:/app/shared-data
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdatabase
    ports:
      - "5433:5432"
    networks:
      - my_network
    restart: always
  frontend:
    build:
      context: ./nextjs-frontend
    user: node
    ports:
      - "3000:3000"
    networks:
      - my_network
    environment:
      NODE_ENV: development
      API_BASE_URL: http://backend:8000
      OPENAPI_OUTPUT_FILE: ./shared-data/openapi.json
    volumes:
      - ./nextjs-frontend:/app
      - nextjs-node-modules:/app/node_modules
      - ./local-shared-data:/app/shared-data
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    networks:
      - my_network

volumes:
  postgres_data:
  nextjs-node-modules:
  fastapi-venv:

networks:
  my_network:
    driver: bridge