"""autogenerate migration after fixing env.py

Revision ID: 492724b8b6c3
Revises: 6cc0486f8b40
Create Date: 2025-07-22 08:06:45.287849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '492724b8b6c3'
down_revision: Union[str, None] = '6cc0486f8b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.alter_column('business_keywords', 'weight',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('business_keywords', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('crawl_tasks', 'target_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crawl_tasks', 'sort_type',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crawl_tasks', 'total_crawled',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crawl_tasks', 'new_notes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crawl_tasks', 'changed_notes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crawl_tasks', 'important_notes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('xhs_comments', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('xhs_comments', 'contains_business_keywords',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('xhs_comments', 'importance_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('xhs_notes', 'liked_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('xhs_notes', 'collected_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('xhs_notes', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('xhs_notes', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('xhs_notes', 'is_new',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('xhs_notes', 'is_changed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('xhs_notes', 'is_important',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('xhs_notes', 'crawl_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_xhs_notes_is_deleted'), 'xhs_notes', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_xhs_notes_is_deleted'), table_name='xhs_notes')
    op.alter_column('xhs_notes', 'crawl_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('xhs_notes', 'is_important',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('xhs_notes', 'is_changed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('xhs_notes', 'is_new',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('xhs_notes', 'share_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('xhs_notes', 'comment_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('xhs_notes', 'collected_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('xhs_notes', 'liked_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('xhs_comments', 'importance_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('xhs_comments', 'contains_business_keywords',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('xhs_comments', 'like_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crawl_tasks', 'important_notes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crawl_tasks', 'changed_notes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crawl_tasks', 'new_notes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crawl_tasks', 'total_crawled',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crawl_tasks', 'sort_type',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crawl_tasks', 'target_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('business_keywords', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('business_keywords', 'weight',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('items',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='items_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    # ### end Alembic commands ###
