"""add author_avatar to xhs_notes

Revision ID: 6cc0486f8b40
Revises: 66c491833c87
Create Date: 2025-07-15 01:04:53.098960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6cc0486f8b40'
down_revision: Union[str, None] = '66c491833c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('xhs_notes', sa.Column('author_avatar', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('xhs_notes', 'author_avatar')
    # ### end Alembic commands ###
